-- Água Delivery - Pedidos Web V1
-- Rode este arquivo no Supabase > SQL Editor > New query > Run.
-- O script cria somente as tabelas do canal web. Não toca no SQLite principal.

create extension if not exists pgcrypto;

create table if not exists public.web_products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.web_customers (
  id uuid primary key default gen_random_uuid(),
  client_token uuid not null unique default gen_random_uuid(),
  name text not null,
  whatsapp text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.web_addresses (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.web_customers(id) on delete cascade,
  street text not null,
  number text not null,
  neighborhood text not null,
  complement text,
  reference text,
  created_at timestamptz not null default now()
);

create table if not exists public.web_orders (
  id bigint generated by default as identity primary key,
  public_token uuid not null unique default gen_random_uuid(),
  customer_id uuid not null references public.web_customers(id),
  address_id uuid not null references public.web_addresses(id),
  payment_method text not null check (payment_method in ('pix','dinheiro','cartao_entrega')),
  change_for numeric(10,2),
  total numeric(10,2) not null check (total >= 0),
  status text not null default 'recebido' check (status in ('recebido','aceito','preparando','saiu_entrega','entregue','cancelado')),
  printed_at timestamptz,
  print_claimed_at timestamptz,
  print_attempts integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.web_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.web_orders(id) on delete cascade,
  product_id bigint references public.web_products(id),
  product_name text not null,
  unit_price numeric(10,2) not null,
  quantity integer not null check (quantity > 0 and quantity <= 99),
  subtotal numeric(10,2) not null
);

create index if not exists idx_web_orders_created on public.web_orders(created_at desc);
create index if not exists idx_web_orders_status on public.web_orders(status);
create index if not exists idx_web_orders_printed on public.web_orders(printed_at, created_at);
create index if not exists idx_web_addresses_customer on public.web_addresses(customer_id, created_at desc);
create index if not exists idx_web_order_items_order on public.web_order_items(order_id);


-- Mantém updated_at sincronizado em alterações administrativas.
create or replace function public.web_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_web_products_updated on public.web_products;
create trigger trg_web_products_updated before update on public.web_products
for each row execute function public.web_touch_updated_at();

drop trigger if exists trg_web_customers_updated on public.web_customers;
create trigger trg_web_customers_updated before update on public.web_customers
for each row execute function public.web_touch_updated_at();

drop trigger if exists trg_web_orders_updated on public.web_orders;
create trigger trg_web_orders_updated before update on public.web_orders
for each row execute function public.web_touch_updated_at();

-- RLS: o navegador pode ler somente produtos ativos. Dados pessoais e pedidos não são expostos diretamente.
alter table public.web_products enable row level security;
alter table public.web_customers enable row level security;
alter table public.web_addresses enable row level security;
alter table public.web_orders enable row level security;
alter table public.web_order_items enable row level security;

revoke all on table public.web_customers, public.web_addresses, public.web_orders, public.web_order_items from anon, authenticated;
revoke all on table public.web_products from anon, authenticated;
grant select on table public.web_products to anon, authenticated;

drop policy if exists web_products_public_read on public.web_products;
create policy web_products_public_read on public.web_products
for select to anon, authenticated
using (active = true);

-- Cria pedido com preço calculado no servidor. O navegador nunca define o preço final.
create or replace function public.place_web_order(
  p_client_token uuid,
  p_name text,
  p_whatsapp text,
  p_street text,
  p_number text,
  p_neighborhood text,
  p_complement text,
  p_reference text,
  p_payment_method text,
  p_change_for numeric,
  p_items jsonb
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_customer_id uuid;
  v_client_token uuid;
  v_address_id uuid;
  v_order_id bigint;
  v_public_token uuid;
  v_total numeric(10,2);
  v_requested integer;
  v_matched integer;
  v_phone text;
begin
  if char_length(trim(coalesce(p_name,''))) < 2 then raise exception 'Nome inválido'; end if;
  v_phone := regexp_replace(coalesce(p_whatsapp,''), '[^0-9]', '', 'g');
  if char_length(v_phone) < 10 or char_length(v_phone) > 13 then raise exception 'WhatsApp inválido'; end if;
  if trim(coalesce(p_street,'')) = '' or trim(coalesce(p_number,'')) = '' or trim(coalesce(p_neighborhood,'')) = '' then raise exception 'Endereço incompleto'; end if;
  if p_payment_method not in ('pix','dinheiro','cartao_entrega') then raise exception 'Forma de pagamento inválida'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then raise exception 'Itens inválidos'; end if;

  if p_client_token is not null then
    select c.id, c.client_token into v_customer_id, v_client_token
      from public.web_customers c where c.client_token = p_client_token limit 1;
  end if;

  if v_customer_id is null then
    v_client_token := gen_random_uuid();
    insert into public.web_customers(client_token,name,whatsapp)
    values(v_client_token, trim(p_name), v_phone)
    returning id into v_customer_id;
  else
    update public.web_customers set name=trim(p_name), whatsapp=v_phone, updated_at=now() where id=v_customer_id;
  end if;

  insert into public.web_addresses(customer_id,street,number,neighborhood,complement,reference)
  values(v_customer_id,trim(p_street),trim(p_number),trim(p_neighborhood),nullif(trim(coalesce(p_complement,'')),''),nullif(trim(coalesce(p_reference,'')),''))
  returning id into v_address_id;

  with req as (
    select (j->>'product_id')::bigint product_id, sum((j->>'quantity')::integer)::integer quantity
    from jsonb_array_elements(p_items) j
    group by (j->>'product_id')::bigint
  ) select count(*) into v_requested from req;

  with req as (
    select (j->>'product_id')::bigint product_id, sum((j->>'quantity')::integer)::integer quantity
    from jsonb_array_elements(p_items) j
    group by (j->>'product_id')::bigint
  )
  select count(*), coalesce(sum(p.price * r.quantity),0)::numeric(10,2)
  into v_matched, v_total
  from req r join public.web_products p on p.id=r.product_id and p.active=true
  where r.quantity between 1 and 99;

  if v_requested <> v_matched or v_total <= 0 then raise exception 'Há produto inválido ou indisponível no carrinho'; end if;
  if p_payment_method='dinheiro' and p_change_for is not null and p_change_for < v_total then raise exception 'O valor para troco deve ser maior ou igual ao total'; end if;

  insert into public.web_orders(customer_id,address_id,payment_method,change_for,total)
  values(v_customer_id,v_address_id,p_payment_method,p_change_for,v_total)
  returning id,public_token into v_order_id,v_public_token;

  insert into public.web_order_items(order_id,product_id,product_name,unit_price,quantity,subtotal)
  select v_order_id,p.id,p.name,p.price,r.quantity,(p.price*r.quantity)::numeric(10,2)
  from (
    select (j->>'product_id')::bigint product_id, sum((j->>'quantity')::integer)::integer quantity
    from jsonb_array_elements(p_items) j
    group by (j->>'product_id')::bigint
  ) r join public.web_products p on p.id=r.product_id and p.active=true;

  return jsonb_build_object(
    'order_id',v_order_id,'public_token',v_public_token,'client_token',v_client_token,
    'total',v_total,'status','recebido','created_at',now()
  );
end;
$$;

-- Recupera o mini cadastro somente com o token aleatório salvo naquele navegador.
create or replace function public.get_web_profile(p_client_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v_result jsonb;
begin
  select jsonb_build_object(
    'name',c.name,'whatsapp',c.whatsapp,
    'street',a.street,'number',a.number,'neighborhood',a.neighborhood,
    'complement',a.complement,'reference',a.reference
  ) into v_result
  from public.web_customers c
  left join lateral (
    select * from public.web_addresses x where x.customer_id=c.id order by x.created_at desc limit 1
  ) a on true
  where c.client_token=p_client_token;
  return v_result;
end;
$$;

-- Acompanha um pedido apenas por um token UUID não sequencial.
create or replace function public.track_web_order(p_public_token uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v_result jsonb;
begin
  select jsonb_build_object(
    'order_id',o.id,'status',o.status,'total',o.total,'payment_method',o.payment_method,
    'created_at',o.created_at,'updated_at',o.updated_at,
    'items',coalesce((select jsonb_agg(jsonb_build_object('name',i.product_name,'quantity',i.quantity,'unit_price',i.unit_price,'subtotal',i.subtotal) order by i.id) from public.web_order_items i where i.order_id=o.id),'[]'::jsonb)
  ) into v_result
  from public.web_orders o where o.public_token=p_public_token;
  return v_result;
end;
$$;

-- Não deixe funções SECURITY DEFINER abertas por padrão.
revoke execute on function public.place_web_order(uuid,text,text,text,text,text,text,text,text,numeric,jsonb) from public;
revoke execute on function public.get_web_profile(uuid) from public;
revoke execute on function public.track_web_order(uuid) from public;
grant execute on function public.place_web_order(uuid,text,text,text,text,text,text,text,text,numeric,jsonb) to anon, authenticated;
grant execute on function public.get_web_profile(uuid) to anon, authenticated;
grant execute on function public.track_web_order(uuid) to anon, authenticated;

-- Produto inicial de teste. Ajuste ou exclua pelo Table Editor depois.
insert into public.web_products(name,description,price,active,sort_order)
select 'Água 20 Litros','Garrafão retornável',6.00,true,1
where not exists (select 1 from public.web_products);
